baseURL = "https://anglersos.github.io/anglersos-web/"
locale = "ru"
title = "AnglersOS Documentation"
theme = "hugo-relearn"
defaultContentLanguage = "ru"

[languages]
  [languages.ru]
    title = "AnglersOS"
    weight = 1
    label = "Русский"

  [languages.en]
    title = "AnglersOS"
    weight = 2
    label = "English"

[params]
  themeVariant = "zen-dark"
  showBreadcrumbs = true
  custom_css = ["css/custom.css"]
  favicon = "images/favicon.png"
  editURL = "https://github.com/AnglersOS/anglersos-web/blob/main/content/"
  
[outputs]
  home = ["html", "rss", "print", "search"]

[[menu.shortcuts]]
  name = "<i class='fab fa-youtube'></i> YouTube"
  url = "https://www.youtube.com/@AnglersOS"
  weight = 1

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub"
  url = "https://github.com/AnglersOS/anglersos-public/"
  weight = 2

  [[languages.en.menu.shortcuts]]
    name = "<i class='fas fa-mug-hot'></i> Buy me a coffee (PayPal)"
    url = "https://www.donationalerts.com/r/anglersos" 
    weight = 1
  [[languages.en.menu.shortcuts]]
    name = "<i class='fas fa-rocket'></i> Become a Member (Boosty)"
    url = "https://boosty.to/anglersos/donate"
    weight = 2


  [[languages.ru.menu.shortcuts]]
    name = "<i class='fas fa-ruble-sign'></i> Поддержать проект (Boosty)"
    url = "https://boosty.to/anglersos/donate"
    weight = 1


  
