baseURL = "https://anglersos.github.io/anglersos-web/"
locale = "ru"
title = "AnglersOS Documentation"
theme = "hugo-relearn"

[languages]
  [languages.en]
    title = "AnglersOS Docs"
    weight = 1
    label = "English"
    contentDir = "content/en"
  [languages.ru]
    title = "Документация AnglersOS"
    weight = 2
    label = "Русский"
    contentDir = "content/ru"

[params]
  themeVariant = "zen-dark"
  showBreadcrumbs = true
  custom_css = ["css/custom.css"]

[outputs]
  home = ["html", "rss", "print", "search"]

[[menu.shortcuts]]
  name = "<i class='fab fa-youtube'></i> YouTube"
  url = "https://www.youtube.com/@AnglersOS"
  weight = 1

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub"
  url = "https://github.com/AnglersOS/anglersos-public/"
  weight = 2
